robot:
  type: so101_follower
  id: xlerobot_left_arm
  disable_torque_on_disconnect: false
  port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A7A058116-if00 # Left PI

 # cameras:
 #   front:
 #     type: opencv
 #     index_or_path: /dev/cam_left
 #     width: 1280
 #     height: 720
 #     fps: 30
 #     warmup_s: 1


teleop:
  type: so101_leader
  port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A7A017922-if00
  id: xlerobot_leader

#display_data: true
