robot:
  id: rosie
  type: xlerobot
  port1: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A7A058116-if00 # Left PI  
  port2: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5A68009991-if00 # Right PI

  cameras:
    left_wrist:
      type: opencv
      index_or_path: /dev/cam_left
      width: 640
      height: 480
      fps: 30
    right_wrist:
      type: opencv
      index_or_path: /dev/cam_right
      width: 640
      height: 480
      fps: 30
    head:
      type: intelrealsense
      serial_number_or_name: "836112060112"
      fps: 30
      width: 1280
      height: 720
      color_mode: BGR
      use_depth: True
